### ISSUE TITLE
rowkey中varchar(12)设置成fixlength

### ISSUE THREAD

**Issue by Adora627** [Kyligence/KAP-manual#218]
rowkey中varchar(12)设置成fixlength，没写参数会导致cube create htable报错。

**Comment by yiming187** [comment]
这个没必要写到手册里，配置fixlength encoding时没有输入参数是错误，这时参数是mandatory，GUI上应该有限制。

**Comment by Adora627** [comment]
https://github.com/Kyligence/KAP/issues/2370
