### ISSUE TITLE
"任务引擎HA配置" 文档有误

### ISSUE THREAD

**Issue by shaofengshi** [Kyligence/KAP-manual#44]
在这篇文档中 http://manual.kyligence.io/v2.3/zh-cn/config/jobengine_ha.cn.html：
提到 kylin.zookeeper.address=host1:2181,host2:2181,host3:2181

但实际上设置此属性无效，是因为属性名被改了，正确的应该是：

kap.job.helix.zookeeper-address=host1:2181,host2:2181,host3:2181

**Comment by yiming187** [comment]
Thanks Shaofeng. resolved for 2.3+
