### ISSUE TITLE
Enable job engine HA document is wrong

### ISSUE THREAD

**Issue by shaofengshi** [Kyligence/KAP-manual#46]
In KAP 2.3, there are many parameters be refactored, while the doc wasn't updated. If follow the http://manual.kyligence.io/v2.3/zh-cn/config/jobengine_ha.cn.html it couldn't work. By checking code, I found:

1. kylin.zookeeper.address --> kap.job.helix.zookeeper-address
2. kylin.enable.scheduler --> kylin.job.scheduler.default

Only after updating to use the new parameters, the HA can work

**Comment by yiming187** [comment]
Thanks @shaofengshi , fixed.
