### ISSUE TITLE
Add Ad-Hoc to insight part

### ISSUE THREAD

**Issue by Adora627** [Kyligence/KAP-manual#61]
整合查询页面内容：

- [ ] 介绍大模块划分，以及查询页面中常用功能
- [ ] 介绍和解释不同场景下的查询反馈的差异和查询速度的差异
- [ ] 总结一般性的适用场景
- [ ] 总结使用注意事项（Nice to have）

**Comment by auphyroc99** [comment]
Please check my PR about description of ad-hoc query.
